#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/qwen3/modular_qwen3.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_qwen3.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 The Qwen team, Alibaba Group and the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Callable, Optional, Union

import torch
from torch import nn

from ...activations import ACT2FN
from ...cache_utils import Cache, DynamicCache
from ...generation import GenerationMixin
from ...integrations import use_kernel_forward_from_hub
from ...masking_utils import create_causal_mask, create_sliding_window_causal_mask
from ...modeling_flash_attention_utils import FlashAttentionKwargs
from ...modeling_layers import (
    GenericForQuestionAnswering,
    GenericForSequenceClassification,
    GenericForTokenClassification,
    GradientCheckpointingLayer,
)
from ...modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast
from ...modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from ...modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from ...processing_utils import Unpack
from ...utils import TransformersKwargs, auto_docstring, can_return_tuple
from ...utils.deprecation import deprecate_kwarg
from ...utils.generic import check_model_inputs
from .configuration_qwen3 import Qwen3ShatteredShards4BConfig
import torch.nn.functional as F  
import math
import warnings
import numpy as np
# 🚀 DISABLE ALL PRINTS IN THIS FILE
def print(*args, **kwargs):
    pass  # Do nothing
class AdaptiveWindowManager:
    def __init__(
        self,
        max_context_length: int = 4096,
        min_window_size: int = 50,
        max_window_size: int = 4096,
        target_efficiency: float = 0.85,
        complexity_threshold: float = 0.7,
        prediction_confidence: float = 0.8,
        adaptation_strategy: str = "dynamic",
    ):
        self.max_context_length = max_context_length
        self.min_window_size = min_window_size
        self.max_window_size = max_window_size
        self.target_efficiency = target_efficiency
        self.complexity_threshold = complexity_threshold
        self.prediction_confidence = prediction_confidence
        self.adaptation_strategy = adaptation_strategy
        
        # State tracking
        self.current_window_size = min_window_size
        self.prompt_complexity_history = []
        self.sequence_length_history = []
        self.efficiency_history = []
    
    def estimate_prompt_complexity(self, token_ids: torch.Tensor, attention_weights: Optional[torch.Tensor] = None) -> float:
        """Estimate the complexity of the input prompt"""
        if len(token_ids.shape) > 1:
            seq_len = token_ids.shape[1]
        else:
            seq_len = len(token_ids)
        
        # Basic complexity factors
        factors = []
        
        # 1. Sequence length factor (normalized)
        length_factor = min(seq_len / self.max_context_length, 1.0)
        factors.append(length_factor)
        
        # 2. Token diversity (vocabulary usage)
        unique_tokens = torch.unique(token_ids).float()
        diversity_factor = len(unique_tokens) / seq_len
        factors.append(diversity_factor)
        
        # 3. Attention pattern complexity (if available)
        if attention_weights is not None:
            attention_entropy = self._calculate_attention_entropy(attention_weights)
            factors.append(attention_entropy)
        else:
            factors.append(0.5)
        
        # 4. Structural complexity (rough estimate based on special tokens)
        special_tokens = torch.sum(token_ids > 30000).float()
        structural_factor = special_tokens / seq_len
        factors.append(structural_factor)
        
        # Weighted combination
        weights = [0.3, 0.25, 0.25, 0.2]
        complexity = sum(w * f for w, f in zip(weights, factors))
        
        return complexity.item()
    
    def _calculate_attention_entropy(self, attention_weights: torch.Tensor) -> float:
        """Calculate entropy of attention patterns"""
        if attention_weights is None:
            return 0.5
        
        # Flatten and normalize
        attn_flat = attention_weights.flatten()
        attn_flat = attn_flat / (attn_flat.sum() + 1e-8)
        
        # Calculate entropy
        entropy = -torch.sum(attn_flat * torch.log(attn_flat + 1e-8))
        max_entropy = math.log(len(attn_flat))
        
        return (entropy / max_entropy).item()
    
    def predict_optimal_window_size(self, current_seq_len: int, prompt_complexity: float, 
                                  historical_data: list[tuple] = None) -> int:
        """Predict optimal window size based on current context"""
        
        if self.adaptation_strategy == "dynamic":
            return self._dynamic_adaptation(current_seq_len, prompt_complexity)
        elif self.adaptation_strategy == "predictive":
            return self._predictive_adaptation(current_seq_len, prompt_complexity, historical_data)
        elif self.adaptation_strategy == "hybrid":
            return self._hybrid_adaptation(current_seq_len, prompt_complexity, historical_data)
        else:
            return self._default_adaptation(current_seq_len, prompt_complexity)
    
    def _dynamic_adaptation(self, current_seq_len: int, prompt_complexity: float) -> int:
        """Dynamic adaptation based on current state"""
        base_size = int(current_seq_len * (1 + prompt_complexity))
        
        # Adjust based on complexity
        if prompt_complexity > self.complexity_threshold:
            window_size = min(base_size * 2, self.max_window_size)
        else:
            window_size = max(base_size, self.min_window_size)
        
        window_size = max(self.min_window_size, min(window_size, self.max_window_size))
        window_size = (window_size + 31) // 64 * 64
        
        return window_size
    
    def _predictive_adaptation(self, current_seq_len: int, prompt_complexity: float, 
                             historical_data: list[tuple]) -> int:
        """Predictive adaptation using historical patterns"""
        if not historical_data or len(historical_data) < 5:
            return self._dynamic_adaptation(current_seq_len, prompt_complexity)
        
        recent_patterns = historical_data[-10:]
        similar_patterns = [pat for pat in recent_patterns 
                          if abs(pat[1] - prompt_complexity) < 0.2]
        
        if similar_patterns:
            optimal_sizes = [pat[2] for pat in similar_patterns]
            predicted_size = int(sum(optimal_sizes) / len(optimal_sizes))
        else:
            predicted_size = self._dynamic_adaptation(current_seq_len, prompt_complexity)
        
        return max(self.min_window_size, min(predicted_size, self.max_window_size))
    
    def _hybrid_adaptation(self, current_seq_len: int, prompt_complexity: float,
                          historical_data: list[tuple]) -> int:
        """Hybrid approach combining dynamic and predictive methods"""
        dynamic_size = self._dynamic_adaptation(current_seq_len, prompt_complexity)
        
        if historical_data and len(historical_data) >= 3:
            predictive_size = self._predictive_adaptation(current_seq_len, prompt_complexity, historical_data)
            hybrid_size = int(0.7 * dynamic_size + 0.3 * predictive_size)
        else:
            hybrid_size = dynamic_size
        
        return hybrid_size
    
    def _default_adaptation(self, current_seq_len: int, prompt_complexity: float) -> int:
        """Default conservative adaptation"""
        if current_seq_len <= self.min_window_size:
            return self.min_window_size
        elif current_seq_len >= self.max_window_size:
            return self.max_window_size
        else:
            scale = (current_seq_len - self.min_window_size) / (self.max_window_size - self.min_window_size)
            window_size = self.min_window_size + scale * (self.max_window_size - self.min_window_size)
            return int(window_size)
    
    def update_adaptive_window(self, token_ids: torch.Tensor, attention_weights: Optional[torch.Tensor] = None,
                             current_efficiency: Optional[float] = None) -> int:
        """Update and return the optimal window size"""
        current_seq_len = token_ids.shape[1] if len(token_ids.shape) > 1 else len(token_ids)
        
        # Estimate prompt complexity
        complexity = self.estimate_prompt_complexity(token_ids, attention_weights)
        self.prompt_complexity_history.append(complexity)
        
        # Predict optimal window size
        historical_data = list(zip(
            self.sequence_length_history[-10:],
            self.prompt_complexity_history[-10:],
            [self.current_window_size] * min(10, len(self.sequence_length_history))
        ))
        
        optimal_window = self.predict_optimal_window_size(
            current_seq_len, complexity, historical_data
        )
        
        # Update current window size with smoothing
        smoothing_factor = 0.3
        self.current_window_size = int(
            smoothing_factor * optimal_window + 
            (1 - smoothing_factor) * self.current_window_size
        )
        
        # Ensure bounds
        self.current_window_size = max(
            self.min_window_size, 
            min(self.current_window_size, self.max_window_size)
        )
        
        # Update history
        self.sequence_length_history.append(current_seq_len)
        if current_efficiency is not None:
            self.efficiency_history.append(current_efficiency)
        
        return self.current_window_size

class DynamicKVCacheManager:
    def __init__(
        self,
        decay_type: str = "exponential",
        importance_metric: str = "attention",
        window_size: int = 2048,
        decay_factor: float = 0.98,
        importance_power: float = 1.2,
        min_decay: float = 0.2,
        enable_importance: bool = True,
        enable_compression: bool = False,
        compression_ratio: float = 0.8,
        # Adaptive window parameters
        enable_adaptive_window: bool = True,  # Disable by default for stability
        max_context_length: int = 4096,
        min_window_size: int = 512,
        max_window_size: int = 4096,
        adaptation_strategy: str = "dynamic"
    ):
        self.window_size = window_size
        self.original_window_size = window_size
        self.decay_factor = decay_factor
        self.importance_power = importance_power
        self.min_decay = min_decay
        self.enable_importance = enable_importance
        self.enable_compression = enable_compression
        self.compression_ratio = compression_ratio
        
        self.prev_attention = None
        self.current_step = 0
        self.current_sequence_length = 0
        
        self.decay_fn = self._get_decay_fn(decay_type)
        self.importance_fn = self._get_importance_fn(importance_metric)
        
        # Adaptive window management - disabled by default
        self.enable_adaptive_window = enable_adaptive_window
        if enable_adaptive_window:
            self.adaptive_manager = AdaptiveWindowManager(
                max_context_length=max_context_length,
                min_window_size=min_window_size,
                max_window_size=max_window_size,
                adaptation_strategy=adaptation_strategy
            )

    def decay_kv_cache(self, keys: torch.Tensor, values: torch.Tensor, 
                      current_step: int, prev_attention: torch.Tensor,
                      token_ids: Optional[torch.Tensor] = None) -> tuple[torch.Tensor, torch.Tensor]:
        """Enhanced decay with proper timing"""
        if keys is None or values is None:
            return keys, values
        
        batch_size, num_heads, seq_len, head_dim = keys.shape
        self.current_sequence_length = seq_len
        self.current_step = current_step
        
        # Update adaptive window size if enabled (less frequently to reduce overhead)
        if self.enable_adaptive_window and token_ids is not None and current_step % 5 == 0:
            self.update_adaptive_window_size(token_ids, prev_attention)
        
        # Only decay tokens that are beyond the recent window
        if seq_len <= self.window_size:
            return keys, values
            
        positions = torch.arange(seq_len, device=keys.device).unsqueeze(0).unsqueeze(0)
        positions = positions.expand(batch_size, num_heads, -1)
        
        position_decay = self.decay_fn(positions, current_step)
        
        if self.enable_importance and prev_attention is not None:
            importance = self.importance_fn(keys, values, prev_attention)
            importance_modulation = importance ** self.importance_power
            combined_decay = position_decay * importance_modulation
        else:
            combined_decay = position_decay
        
        combined_decay = combined_decay.unsqueeze(-1)
        
        # Use in-place operations to save memory
        decayed_keys = keys * combined_decay
        decayed_values = values * combined_decay
        
        return decayed_keys, decayed_values

    def exponential_decay(self, positions: torch.Tensor, current_step: int) -> torch.Tensor:
        """Simplified exponential decay - most effective"""
        decay_start = max(0, current_step - self.window_size)
        relative_positions = positions - decay_start
        decay_factors = self.decay_factor ** torch.clamp(relative_positions, 0, self.window_size)
        decay_factors = torch.clamp(decay_factors, self.min_decay, 1.0)
        return decay_factors

    def attention_importance(self, keys: torch.Tensor, values: torch.Tensor, prev_attention: torch.Tensor) -> torch.Tensor:
        """Simplified importance calculation"""
        if prev_attention is None:
            batch_size, num_heads, seq_len = keys.shape[0], keys.shape[1], keys.shape[2]
            return torch.ones(batch_size, num_heads, seq_len, device=keys.device)
        
        # Use recent attention patterns
        importance = prev_attention.unsqueeze(-1).expand(-1, -1, keys.shape[2])
        importance = importance / (importance.sum(dim=-1, keepdim=True) + 1e-8)
        return importance
        
    def magnitude_importance(self, keys: torch.Tensor, values: torch.Tensor, prev_attention: torch.Tensor) -> torch.Tensor:
        key_norms = torch.norm(keys, dim=-1)
        importance = key_norms / (key_norms.sum(dim=-1, keepdim=True) + 1e-8)
        return importance
    
    def random_importance(self, keys: torch.Tensor, values: torch.Tensor, prev_attention: torch.Tensor) -> torch.Tensor:
        batch_size, num_heads, seq_len = keys.shape[0], keys.shape[1], keys.shape[2]
        importance = torch.rand(batch_size, num_heads, seq_len, device=keys.device)
        importance = importance / (importance.sum(dim=-1, keepdim=True) + 1e-8)
        return importance
    
    def learned_importance(self, keys: torch.Tensor, values: torch.Tensor, prev_attention: torch.Tensor) -> torch.Tensor:
        """Importance based on learned patterns"""
        if prev_attention is None:
            batch_size, num_heads, seq_len = keys.shape[0], keys.shape[1], keys.shape[2]
            return torch.ones(batch_size, num_heads, seq_len, device=keys.device)
        
        # Combine attention with key magnitude
        attention_importance = prev_attention.detach()
        key_magnitude = torch.norm(keys, dim=-1)
        
        # Normalize both
        attention_importance = attention_importance / (attention_importance.sum(dim=-1, keepdim=True) + 1e-8)
        key_magnitude = key_magnitude / (key_magnitude.sum(dim=-1, keepdim=True) + 1e-8)
        
        # Combined importance
        combined_importance = 0.7 * attention_importance + 0.3 * key_magnitude
        combined_importance = combined_importance / (combined_importance.sum(dim=-1, keepdim=True) + 1e-8)
        
        return combined_importance
    
    def update_adaptive_window_size(self, token_ids: torch.Tensor, attention_weights: Optional[torch.Tensor] = None):
        """Update the window size adaptively"""
        if not self.enable_adaptive_window:
            return self.window_size
        
        # Calculate current efficiency
        current_efficiency = self._calculate_current_efficiency()
        
        # Update adaptive window
        new_window_size = self.adaptive_manager.update_adaptive_window(
            token_ids, attention_weights, current_efficiency
        )
        
        # Update the window size
        self.window_size = new_window_size
        return new_window_size
    
    def _calculate_current_efficiency(self) -> float:
        """Calculate current cache efficiency"""
        if self.current_sequence_length == 0:
            return 1.0
        
        efficiency = min(1.0, self.window_size / self.current_sequence_length)
        return efficiency
    
    def decay_kv_cache(self, keys: torch.Tensor, values: torch.Tensor, 
                      current_step: int, prev_attention: torch.Tensor,
                      token_ids: Optional[torch.Tensor] = None) -> tuple[torch.Tensor, torch.Tensor]:
        """Enhanced decay with adaptive window sizing"""
        if keys is None or values is None:
            return keys, values
        
        batch_size, num_heads, seq_len, head_dim = keys.shape
        self.current_sequence_length = seq_len
        self.current_step = current_step
        
        # Update adaptive window size if enabled
        if self.enable_adaptive_window and token_ids is not None:
            self.update_adaptive_window_size(token_ids, prev_attention)
        
        positions = torch.arange(seq_len, device=keys.device).unsqueeze(0).unsqueeze(0)
        positions = positions.expand(batch_size, num_heads, -1)
        
        position_decay = self.decay_fn(positions, current_step)
        
        if self.enable_importance:
            importance = self.importance_fn(keys, values, prev_attention)
            importance_modulation = importance ** self.importance_power
            combined_decay = position_decay * importance_modulation
        else:
            combined_decay = position_decay
        
        combined_decay = combined_decay.unsqueeze(-1)
        
        decayed_keys = keys * combined_decay
        decayed_values = values * combined_decay
        
        return decayed_keys, decayed_values

    def get_cache_stats(self) -> dict[str, any]:
        """Get current cache statistics"""
        stats = {
            'current_step': self.current_step,
            'current_sequence_length': self.current_sequence_length,
            'window_size': self.window_size,
            'enable_adaptive_window': self.enable_adaptive_window,
            'enable_importance': self.enable_importance,
        }
        
        if self.enable_adaptive_window:
            stats.update({
                'adaptive_window_size': self.adaptive_manager.current_window_size,
                'min_window_size': self.adaptive_manager.min_window_size,
                'max_window_size': self.adaptive_manager.max_window_size,
            })
        
        return stats

@use_kernel_forward_from_hub("RMSNorm")
class Qwen3RMSNorm(nn.Module):
    def __init__(self, hidden_size, eps: float = 1e-6) -> None:
        """
        Qwen3RMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class Qwen3MLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.up_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias=False)
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
        return down_proj


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


def apply_rotary_pos_emb(q, k, cos, sin, position_ids=None, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        position_ids (`torch.Tensor`, *optional*):
            Deprecated and unused.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: Optional[torch.Tensor],
    scaling: float,
    dropout: float = 0.0,
    **kwargs: Unpack[TransformersKwargs],
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        causal_mask = attention_mask[:, :, :, : key_states.shape[-2]]
        attn_weights = attn_weights + causal_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


class Qwen3Attention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: Qwen3ShatteredShards4BConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        self.is_causal = True

        self.q_proj = nn.Linear(
            config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.attention_bias
        )
        self.k_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.v_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.o_proj = nn.Linear(
            config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.attention_bias
        )
        self.q_norm = Qwen3RMSNorm(self.head_dim, eps=config.rms_norm_eps)
        self.k_norm = Qwen3RMSNorm(self.head_dim, eps=config.rms_norm_eps)
        self.sliding_window = config.sliding_window if config.layer_types[layer_idx] == "sliding_attention" else None

        # Dynamic KV Cache Manager
        self.kv_cache_manager = None
        if hasattr(config, 'enable_dynamic_kv_cache') and config.enable_dynamic_kv_cache:
            kv_config = getattr(config, 'dynamic_kv_config', {})
            self.kv_cache_manager = DynamicKVCacheManager(**kv_config)

    @deprecate_kwarg("past_key_value", new_name="past_key_values", version="4.58")
    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: Optional[torch.Tensor],
        past_key_values: Optional[Cache] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> tuple[torch.Tensor, Optional[torch.Tensor]]:
        input_shape = hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)

        query_states = self.q_norm(self.q_proj(hidden_states).view(hidden_shape)).transpose(1, 2)
        key_states = self.k_norm(self.k_proj(hidden_states).view(hidden_shape)).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(hidden_shape).transpose(1, 2)

        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

        # 🚀 CRITICAL FIX: Apply decay BEFORE attention computation and cache update
        current_step = 0
        if past_key_values is not None:
            current_step = past_key_values.get_seq_length() if hasattr(past_key_values, 'get_seq_length') else 0
            
            # Apply decay to existing cache BEFORE using it for attention
            if (self.kv_cache_manager is not None and 
                past_key_values is not None and
                self.layer_idx in past_key_values.key_cache):
                
                current_keys = past_key_values.key_cache[self.layer_idx]
                current_values = past_key_values.value_cache[self.layer_idx]
                
                if current_keys is not None:
                    # 🎯 DECAY FIRST, then use for attention
                    decayed_keys, decayed_values = self.kv_cache_manager.decay_kv_cache(
                        current_keys, current_values, 
                        self.kv_cache_manager.current_step,
                        self.kv_cache_manager.prev_attention
                    )
                    past_key_values.key_cache[self.layer_idx] = decayed_keys
                    past_key_values.value_cache[self.layer_idx] = decayed_values

        # Now update cache with current states (AFTER decay but BEFORE attention)
        if past_key_values is not None:
            cache_kwargs = {"sin": sin, "cos": cos, "cache_position": cache_position}
            key_states, value_states = past_key_values.update(key_states, value_states, self.layer_idx, cache_kwargs)

        attention_interface: Callable = eager_attention_forward
        if self.config._attn_implementation != "eager":
            attention_interface = ALL_ATTENTION_FUNCTIONS[self.config._attn_implementation]

        # Compute attention using the DECAYED cache + new tokens
        attn_output, attn_weights = attention_interface(
            self,
            query_states,
            key_states,
            value_states,
            attention_mask,
            dropout=0.0 if not self.training else self.attention_dropout,
            scaling=self.scaling,
            sliding_window=self.sliding_window,
            **kwargs,
        )

        # Store attention for NEXT step's decay (current step is already processed)
        if self.kv_cache_manager is not None and attn_weights is not None:
            # Store compressed attention for next step
            attention_summary = attn_weights.mean(dim=-1).detach()  # [batch, heads]
            self.kv_cache_manager.prev_attention = attention_summary
            
            # Update step counter for next iteration
            self.kv_cache_manager.current_step = current_step + 1

        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        attn_output = self.o_proj(attn_output)
        return attn_output, attn_weights


class Qwen3DecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: Qwen3ShatteredShards4BConfig, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size

        self.self_attn = Qwen3Attention(config=config, layer_idx=layer_idx)

        self.mlp = Qwen3MLP(config)
        self.input_layernorm = Qwen3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = Qwen3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.attention_type = config.layer_types[layer_idx]

    @deprecate_kwarg("past_key_value", new_name="past_key_values", version="4.58")
    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        use_cache: Optional[bool] = False,
        cache_position: Optional[torch.LongTensor] = None,
        position_embeddings: Optional[tuple[torch.Tensor, torch.Tensor]] = None,  # necessary, but kept here for BC
        **kwargs: Unpack[TransformersKwargs],
    ) -> torch.Tensor:
        residual = hidden_states
        hidden_states = self.input_layernorm(hidden_states)
        # Self Attention
        hidden_states, _ = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            use_cache=use_cache,
            cache_position=cache_position,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        hidden_states = residual + hidden_states

        # Fully Connected
        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)
        hidden_states = self.mlp(hidden_states)
        hidden_states = residual + hidden_states
        return hidden_states


@auto_docstring
class Qwen3PreTrainedModel(PreTrainedModel):
    config: Qwen3ShatteredShards4BConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["Qwen3DecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn = True
    _supports_sdpa = True
    _supports_flex_attn = True

    _can_compile_fullgraph = True
    _supports_attention_backend = True
    _can_record_outputs = {
        "hidden_states": Qwen3DecoderLayer,
        "attentions": Qwen3Attention,
    }


class Qwen3RotaryEmbedding(nn.Module):
    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    def __init__(self, config: Qwen3ShatteredShards4BConfig, device=None):
        super().__init__()
        # BC: "rope_type" was originally "type"
        if hasattr(config, "rope_scaling") and isinstance(config.rope_scaling, dict):
            self.rope_type = config.rope_scaling.get("rope_type", config.rope_scaling.get("type"))
        else:
            self.rope_type = "default"
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config
        self.rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]

        inv_freq, self.attention_scaling = self.rope_init_fn(self.config, device)
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.original_inv_freq = self.inv_freq

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with torch.autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


@auto_docstring
class Qwen3Model(Qwen3PreTrainedModel):
    def __init__(self, config: Qwen3ShatteredShards4BConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [Qwen3DecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = Qwen3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = Qwen3RotaryEmbedding(config=config)
        self.gradient_checkpointing = False
        self.has_sliding_layers = "sliding_attention" in self.config.layer_types

        # Initialize weights and apply final processing
        self.post_init()

    @check_model_inputs
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPast:
        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache(config=self.config)

        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens, past_seen_tokens + inputs_embeds.shape[1], device=inputs_embeds.device
            )

        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)

        # It may already have been prepared by e.g. `generate`
        if not isinstance(causal_mask_mapping := attention_mask, dict):
            # Prepare mask arguments
            mask_kwargs = {
                "config": self.config,
                "input_embeds": inputs_embeds,
                "attention_mask": attention_mask,
                "cache_position": cache_position,
                "past_key_values": past_key_values,
                "position_ids": position_ids,
            }
            # Create the masks
            causal_mask_mapping = {
                "full_attention": create_causal_mask(**mask_kwargs),
            }
            # The sliding window alternating layers are not always activated depending on the config
            if self.has_sliding_layers:
                causal_mask_mapping["sliding_attention"] = create_sliding_window_causal_mask(**mask_kwargs)

        hidden_states = inputs_embeds

        # create position embeddings to be shared across the decoder layers
        position_embeddings = self.rotary_emb(hidden_states, position_ids)

        for decoder_layer in self.layers[: self.config.num_hidden_layers]:
            hidden_states = decoder_layer(
                hidden_states,
                attention_mask=causal_mask_mapping[decoder_layer.attention_type],
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                **kwargs,
            )

        hidden_states = self.norm(hidden_states)
        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values if use_cache else None,
        )


@auto_docstring
class ShatteredShardsQwen3ForCausalLM(Qwen3PreTrainedModel, GenerationMixin):
    _tied_weights_keys = ["lm_head.weight"]
    _tp_plan = {"lm_head": "colwise_rep"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config):
        super().__init__(config)
        self.model = Qwen3Model(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)

        # Initialize weights and apply final processing
        self.post_init()

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        **kwargs: Unpack[TransformersKwargs],
    ) -> CausalLMOutputWithPast:
        r"""
        labels (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
            Labels for computing the masked language modeling loss. Indices should either be in `[0, ...,
            config.vocab_size]` or -100 (see `input_ids` docstring). Tokens with indices set to `-100` are ignored
            (masked), the loss is only computed for the tokens with labels in `[0, ..., config.vocab_size]`.

        Example:

        ```python
        >>> from transformers import AutoTokenizer, Qwen3ForCausalLM

        >>> model = Qwen3ForCausalLM.from_pretrained("Qwen/Qwen3-8B")
        >>> tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3-8B")

        >>> prompt = "Hey, are you conscious? Can you talk to me?"
        >>> inputs = tokenizer(prompt, return_tensors="pt")

        >>> # Generate
        >>> generate_ids = model.generate(inputs.input_ids, max_length=30)
        >>> tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
        "Hey, are you conscious? Can you talk to me?\nI'm not conscious, but I can talk to you."
        ```"""
        outputs: BaseModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            cache_position=cache_position,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **kwargs)

        return CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )


class Qwen3ForSequenceClassification(GenericForSequenceClassification, Qwen3PreTrainedModel):
    pass


class Qwen3ForTokenClassification(GenericForTokenClassification, Qwen3PreTrainedModel):
    pass


class Qwen3ForQuestionAnswering(GenericForQuestionAnswering, Qwen3PreTrainedModel):
    base_model_prefix = "transformer"  # For BC, where `transformer` was used instead of `model`


__all__ = [
    "ShatteredShardsQwen3ForCausalLM",
    "Qwen3ForQuestionAnswering",
    "Qwen3PreTrainedModel",
    "Qwen3Model",
    "Qwen3ForSequenceClassification",
    "Qwen3ForTokenClassification",
]